version: '3'
services:
  mysql_server:
    image: mysql
    container_name: container_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${DB_NAME}
    restart: always
    ports:
      - "3306:3306"

  redis_server:
    image: redis
    container_name: container_redis
    restart: always
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=redis_server
    ports:
      - "8081:8081"
