version: '3'
services:
  mysql_server:
    image: mysql
    container_name: container_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
