name: api-dev
services:
  postgres_server:
    image: postgres:latest
    container_name: container_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - "5432:5432"
#    volumes:
#      - pg_data:/var/lib/postgresql/data

  redis_server:
    image: redis:latest
    container_name: container_redis
    restart: always
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: container_redis_commander
    hostname: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=redis_server
    ports:
      - "8081:8081"

#  jaeger_service:
#    image: jaegertracing/all-in-one:latest
#    container_name: container_jaeger
#    restart: always
#    environment:
#      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
#      COLLECTOR_OTLP_ENABLED: "true"
#    ports:
#      - "16686:16686"
#      - "4317:4317"
