[tool.poetry]
name = "api-library"
version = "0.1.0"
description = ""
authors = ["Jorge Vasconcelos <jorge.r.p.v@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "*"
uvicorn = "*"
rich = "*"
python-dotenv = "*"
SQLAlchemy = "*"
SQLAlchemy-serializer = "*"
mysql-connector-python = "*"
python-multipart = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
